spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/biblionet-db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgresSQLDialect
  mail:
    host: localhost
    port: 1025
    username: prox
    password: prox
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enabled: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/biblionets"
application:
  file:
    uploads:
      photos-output-path: ./uploads

server:
  port:8080
